import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Navbar from "./Components/NavBar";
import Footer from "./Components/Footer";
export const metadata = {
  title: "Luxury Properties",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-7xl  mx-auto ">
          <Navbar />
        </div>

        {children}
      </body>
      
    </html>
  );
}
