const data = [
  {
    id: 1,
    title: "Sea View Luxury",
    img: "/s_1.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 25000000,
    address: "Marine Drive, Mumbai",
    type: "buy",
  },
  {
    id: 2,
    title: "Cozy 2BHK Central",
    img: "/s_2.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 8000000,
    address: "Koramangala, Bangalore",
    type: "buy",
  },
  {
    id: 3,
    title: "Elegant Villa Pool",
    img: "/s_3.jpg",
    bedrooms: 4,
    bathrooms: 3,
    price: 35000000,
    address: "Whitefield, Bangalore",
    type: "buy",
  },
  {
    id: 4,
    title: "Charming Hill Cottage",
    img: "/s_4.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 12000000,
    address: "Munnar, Kerala",
    type: "buy",
  },
  {
    id: 5,
    title: "Modern Office Delhi",
    img: "/s_5.jpg",
    bedrooms: 0,
    bathrooms: 0,
    price: 22000000,
    address: "Connaught Place, Delhi",
    type: "buy",
  },
  {
    id: 6,
    title: "Spacious 3BHK Pune",
    img: "/s_6.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 9500000,
    address: "Kalyani Nagar, Pune",
    type: "buy",
  },
  {
    id: 7,
    title: "Chic Studio Apt",
    img: "/s_7.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 5000000,
    address: "Banjara Hills, Hyderabad",
    type: "buy",
  },
  {
    id: 8,
    title: "Luxury Penthouse Mumbai",
    img: "/s_8.jpg",
    bedrooms: 5,
    bathrooms: 4,
    price: 75000000,
    address: "Bandra, Mumbai",
    type: "buy",
  },
  {
    id: 9,
    title: "Affordable Ahmedabad",
    img: "/s_9.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 3500000,
    address: "Gota, Ahmedabad",
    type: "buy",
  },
  {
    id: 10,
    title: "Contemporary Garden Home",
    img: "/s_10.jpg",
    bedrooms: 4,
    bathrooms: 3,
    price: 18000000,
    address: "Chennai, Tamil Nadu",
    type: "buy",
  },
  {
    id: 11,
    title: "Elegant Kolkata Apt",
    img: "/s_11.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 12000000,
    address: "Salt Lake, Kolkata",
    type: "buy",
  },
  {
    id: 12,
    title: "Beautiful Farmhouse Views",
    img: "/s_12.jpg",
    bedrooms: 5,
    bathrooms: 4,
    price: 22000000,
    address: "Nashik, Maharashtra",
    type: "buy",
  },
  {
    id: 13,
    title: "Sunny 2BHK Noida",
    img: "/s_13.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 7000000,
    address: "Sector 18, Noida",
    type: "buy",
  },
  {
    id: 14,
    title: "Traditional Jaipur Home",
    img: "/s_14.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 8000000,
    address: "C-Scheme, Jaipur",
    type: "buy",
  },
  {
    id: 15,
    title: "Modern Chandigarh Studio",
    img: "/s_15.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 6000000,
    address: "Sector 17, Chandigarh",
    type: "buy",
  },
  {
    id: 16,
    title: "Luxurious 4BHK Gurgaon",
    img: "/s_16.jpg",
    bedrooms: 4,
    bathrooms: 3,
    price: 30000000,
    address: "DLF Phase 5, Gurgaon",
    type: "buy",
  },
  {
    id: 17,
    title: "Compact 1BHK Faridabad",
    img: "/s_17.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 4000000,
    address: "Sector 15, Faridabad",
    type: "buy",
  },
  {
    id: 18,
    title: "Stylish Loft Bengaluru",
    img: "/s_18.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 9000000,
    address: "Indiranagar, Bengaluru",
    type: "buy",
  },
  {
    id: 19,
    title: "Scenic Coorg Retreat",
    img: "/s_19.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 13000000,
    address: "Coorg, Karnataka",
    type: "buy",
  },
  {
    id: 20,
    title: "Urban Mumbai Apartment",
    img: "/s_20.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 16000000,
    address: "Powai, Mumbai",
    type: "buy",
  },
  {
    id: 21,
    title: "Cozy Studio",
    img: "/r_1.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 30000,
    address: "Downtown, Mumbai",
    type: "rent",
  },
  {
    id: 22,
    title: "Modern 1BHK",
    img: "/r_2.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 25000,
    address: "Suburbs, Bangalore",
    type: "rent",
  },
  {
    id: 23,
    title: "Spacious 2BHK",
    img: "/r_3.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 50000,
    address: "Near Park, Bangalore",
    type: "rent",
  },
  {
    id: 24,
    title: "Comfortable 2BHK",
    img: "/r_4.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 70000,
    address: "City Center, Mumbai",
    type: "rent",
  },
  {
    id: 25,
    title: "Affordable 1BHK",
    img: "/r_5.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 20000,
    address: "Quiet Area, Delhi",
    type: "rent",
  },
  {
    id: 26,
    title: "Elegant Studio",
    img: "/r_6.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 35000,
    address: "Modern, Pune",
    type: "rent",
  },
  {
    id: 27,
    title: "Bright 2BHK",
    img: "/r_7.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 60000,
    address: "With Balcony, Hyderabad",
    type: "rent",
  },
  {
    id: 28,
    title: "Stylish Studio",
    img: "/r_8.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 40000,
    address: "High-Rise, Mumbai",
    type: "rent",
  },
  {
    id: 29,
    title: "Charming 2BHK",
    img: "/r_9.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 75000,
    address: "Near Mall, Ahmedabad",
    type: "rent",
  },
  {
    id: 30,
    title: "Renovated 1BHK",
    img: "/r_10.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 30000,
    address: "Historic, Chennai",
    type: "rent",
  },
  {
    id: 31,
    title: "Comfy 2BHK",
    img: "/r_11.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 55000,
    address: "Family Area, Kolkata",
    type: "rent",
  },
  
];

export default data;
