const data = [
  {
    id: 1,
    title: "Sea View Luxury",
    img: "/s_1.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 25000000,
    address: "Marine Drive, Mumbai",
  },
  {
    id: 2,
    title: "Cozy 2BHK Central",
    img: "/s_2.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 8000000,
    address: "Koramangala, Bangalore",
  },
  {
    id: 3,
    title: "Elegant Villa Pool",
    img: "/s_3.jpg",
    bedrooms: 4,
    bathrooms: 3,
    price: 35000000,
    address: "Whitefield, Bangalore",
  },
  {
    id: 4,
    title: "Charming Hill Cottage",
    img: "/s_4.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 12000000,
    address: "Munnar, Kerala",
  },
  {
    id: 5,
    title: "Modern Office Delhi",
    img: "/s_5.jpg",
    bedrooms: 0,
    bathrooms: 0,
    price: 22000000,
    address: "Connaught Place, Delhi",
  },
  {
    id: 6,
    title: "Spacious 3BHK Pune",
    img: "/s_6.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 9500000,
    address: "Kalyani Nagar, Pune",
  },
  {
    id: 7,
    title: "Chic Studio Apt",
    img: "/s_7.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 5000000,
    address: "Banjara Hills, Hyderabad",
  },
  {
    id: 8,
    title: "Luxury Penthouse Mumbai",
    img: "/s_8.jpg",
    bedrooms: 5,
    bathrooms: 4,
    price: 75000000,
    address: "Bandra, Mumbai",
  },
  {
    id: 9,
    title: "Affordable Ahmedabad",
    img: "/s_9.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 3500000,
    address: "Gota, Ahmedabad",
  },
  {
    id: 10,
    title: "Contemporary Garden Home",
    img: "/s_10.jpg",
    bedrooms: 4,
    bathrooms: 3,
    price: 18000000,
    address: "Chennai, Tamil Nadu",
  },
  {
    id: 11,
    title: "Elegant Kolkata Apt",
    img: "/s_11.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 12000000,
    address: "Salt Lake, Kolkata",
  },
  {
    id: 12,
    title: "Beautiful Farmhouse Views",
    img: "/s_12.jpg",
    bedrooms: 5,
    bathrooms: 4,
    price: 22000000,
    address: "Nashik, Maharashtra",
  },
  {
    id: 13,
    title: "Sunny 2BHK Noida",
    img: "/s_13.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 7000000,
    address: "Sector 18, Noida",
  },
  {
    id: 14,
    title: "Traditional Jaipur Home",
    img: "/s_14.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 8000000,
    address: "C-Scheme, Jaipur",
  },
  {
    id: 15,
    title: "Modern Chandigarh Studio",
    img: "/s_15.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 6000000,
    address: "Sector 17, Chandigarh",
  },
  {
    id: 16,
    title: "Luxurious 4BHK Gurgaon",
    img: "/s_16.jpg",
    bedrooms: 4,
    bathrooms: 3,
    price: 30000000,
    address: "DLF Phase 5, Gurgaon",
  },
  {
    id: 17,
    title: "Compact 1BHK Faridabad",
    img: "/s_17.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 4000000,
    address: "Sector 15, Faridabad",
  },
  {
    id: 18,
    title: "Stylish Loft Bengaluru",
    img: "/s_18.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 9000000,
    address: "Indiranagar, Bengaluru",
  },
  {
    id: 19,
    title: "Scenic Coorg Retreat",
    img: "/s_19.jpg",
    bedrooms: 3,
    bathrooms: 2,
    price: 13000000,
    address: "Coorg, Karnataka",
  },
  {
    id: 20,
    title: "Urban Mumbai Apartment",
    img: "/s_20.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 16000000,
    address: "Powai, Mumbai",
  },
];

export default data;
