const rentalData = [
  {
    id: 1,
    title: "Cozy Studio",
    img: "/r_1.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 30000,
    address: "Downtown, Mumbai",
  },
  {
    id: 2,
    title: "Modern 1BHK",
    img: "/r_2.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 25000,
    address: "Suburbs, Bangalore",
  },
  {
    id: 3,
    title: "Spacious 2BHK",
    img: "/r_3.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 50000,
    address: "Near Park, Bangalore",
  },
  {
    id: 4,
    title: "Comfortable 2BHK",
    img: "/r_4.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 70000,
    address: "City Center, Mumbai",
  },
  {
    id: 5,
    title: "Affordable 1BHK",
    img: "/r_5.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 20000,
    address: "Quiet Area, Delhi",
  },
  {
    id: 6,
    title: "Elegant Studio",
    img: "/r_6.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 35000,
    address: "Modern, Pune",
  },
  {
    id: 7,
    title: "Bright 2BHK",
    img: "/r_7.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 60000,
    address: "With Balcony, Hyderabad",
  },
  {
    id: 8,
    title: "Stylish Studio",
    img: "/r_8.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 40000,
    address: "High-Rise, Mumbai",
  },
  {
    id: 9,
    title: "Charming 2BHK",
    img: "/r_9.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 75000,
    address: "Near Mall, Ahmedabad",
  },
  {
    id: 10,
    title: "Renovated 1BHK",
    img: "/r_10.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 30000,
    address: "Historic, Chennai",
  },
  {
    id: 11,
    title: "Comfy 2BHK",
    img: "/r_11.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 55000,
    address: "Family Area, Kolkata",
  },
  {
    id: 12,
    title: "Newly Built",
    img: "/r_12.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 40000,
    address: "With Parking, Nashik",
  },
  {
    id: 13,
    title: "Sunny 2BHK",
    img: "/r_13.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 65000,
    address: "Vibrant, Noida",
  },
  {
    id: 14,
    title: "Quaint 1BHK",
    img: "/r_14.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 25000,
    address: "Private, Jaipur",
  },
  {
    id: 15,
    title: "Modern 2BHK",
    img: "/r_15.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 70000,
    address: "Large Windows, Chandigarh",
  },
  {
    id: 16,
    title: "Luxury 1BHK",
    img: "/r_16.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 50000,
    address: "Prime Location, Gurgaon",
  },
  {
    id: 17,
    title: "Compact 1BHK",
    img: "/r_17.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 22000,
    address: "Central Area, Faridabad",
  },
  {
    id: 18,
    title: "Bright 2BHK",
    img: "/r_18.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 55000,
    address: "Garden View, Bengaluru",
  },
  {
    id: 19,
    title: "Spacious 1BHK",
    img: "/r_19.jpg",
    bedrooms: 1,
    bathrooms: 1,
    price: 35000,
    address: "Peaceful Setting, Coorg",
  },
  {
    id: 20,
    title: "Elegant 2BHK",
    img: "/r_20.jpg",
    bedrooms: 2,
    bathrooms: 2,
    price: 90000,
    address: "Urban Area, Mumbai",
  },
];

export default rentalData;
