const Singlepagedata = [
    {
      id: 1,
      type: 'rent',
      title: "Luxurious Apartment with Sea View",
      images: ["/s_1.jpg", "/s_1_1.jpg", "/s_1_2.jpg", "/s_1_3.jpg"],
      bedrooms: 3,
      bathrooms: 2,
      price: 25000000,
      address: "Marine Drive, Mumbai, Maharashtra",
      latitude: 18.925,
      longitude: 72.8238,
      size: 261,
      school: "250m away",
      bus: "100m away",
      restaurant: "50m away",
      description: "Experience opulence and elegance in this stunning apartment featuring breathtaking sea views, modern amenities, and spacious living areas.",
      ownerName: "Ravi Patel",
      ownerPhoto: "/o_1.jpg",
      renterResponsibility: "Utilities are the responsibility of the renter, including water, gas, and electricity.",
      petPolicy: "Pets are welcome with an additional pet deposit.",
      propertyFees: "Must show proof of household income that is at least three times the rent amount.",
    },
    {
      id: 2,
      title: "Cozy 2BHK in Central Bangalore",
      images: ["/s_2.jpg", "/s_2_1.jpg", "/s_2_2.jpg", "/s_2_3.jpg"],
      bedrooms: 2,
      bathrooms: 2,
      price: 8000000,
      address: "Koramangala, Bangalore, Karnataka",
      latitude: 12.9333,
      longitude: 77.6101,
      size: 120,
      school: "300m away",
      bus: "200m away",
      restaurant: "100m away",
      description: "This charming 2BHK apartment offers a cozy and comfortable living space in the heart of Bangalore's vibrant Koramangala neighborhood.",
      ownerName: "Sanjay Kumar",
      ownerPhoto: "/o_2.jpg",
      renterResponsibility: "Tenant is responsible for all utility bills including electricity and water.",
      petPolicy: "Pets are allowed with prior approval and a pet fee.",
      propertyFees: "Requires total household income to be three times the rent.",
    },
    {
      id: 3,
      title: "Elegant Villa with Private Pool",
      images: ["/s_3.jpg", "/s_3_1.jpg", "/s_3_2.jpg", "/s_3_3.jpg"],
      bedrooms: 4,
      bathrooms: 3,
      price: 35000000,
      address: "Whitefield, Bangalore, Karnataka",
      latitude: 12.9762,
      longitude: 77.7038,
      size: 350,
      school: "500m away",
      bus: "150m away",
      restaurant: "200m away",
      description: "This luxurious villa features a private pool, expansive garden, and elegant design, providing an exquisite living experience in Whitefield.",
      ownerName: "Amit Sharma",
      ownerPhoto: "/o_3.jpg",
      renterResponsibility: "Renter must manage utility expenses including water and power.",
      petPolicy: "Pets allowed with a pet deposit and management approval.",
      propertyFees: "Proof of income must be three times the rent to qualify.",
    },
    {
      id: 4,
      title: "Charming Cottage in Hill Station",
      images: ["/s_4.jpg", "/s_4_1.jpg", "/s_4_2.jpg", "/s_4_3.jpg"],
      bedrooms: 3,
      bathrooms: 2,
      price: 12000000,
      address: "Munnar, Kerala",
      latitude: 10.0889,
      longitude: 77.0624,
      size: 180,
      school: "1km away",
      bus: "500m away",
      restaurant: "300m away",
      description: "Escape to this delightful cottage nestled in the picturesque hill station of Munnar, offering a cozy retreat amidst lush green landscapes.",
      ownerName: "Neha Nair",
      ownerPhoto: "/o_4.jpg",
      renterResponsibility: "Utilities are the tenant's responsibility, including maintenance fees.",
      petPolicy: "Pets allowed with prior consent and a pet fee.",
      propertyFees: "Must provide evidence of income at least three times the rent.",
    },
    {
      id: 5,
      title: "Modern Office Space in Delhi",
      images: ["/s_5.jpg", "/s_5_1.jpg", "/s_5_2.jpg", "/s_5_3.jpg"],
      bedrooms: 0,
      bathrooms: 0,
      price: 22000000,
      address: "Connaught Place, Delhi",
      latitude: 28.6328,
      longitude: 77.2198,
      size: 400,
      school: "Nearby",
      bus: "100m away",
      restaurant: "50m away",
      description: "This contemporary office space in the heart of Delhi's Connaught Place is ideal for businesses looking for a prime location with modern facilities.",
      ownerName: "Vikram Singh",
      ownerPhoto: "/o_5.jpg",
      renterResponsibility: "Occupant is accountable for all utilities and service charges.",
      petPolicy: "Pets not allowed in office premises.",
      propertyFees: "Proof of income must be at least three times the monthly rent.",
    },
    {
      id: 6,
      title: "Spacious 3BHK in Pune",
      images: ["/s_6.jpg", "/s_6_1.jpg", "/s_6_2.jpg", "/s_6_3.jpg"],
      bedrooms: 3,
      bathrooms: 2,
      price: 9500000,
      address: "Kalyani Nagar, Pune, Maharashtra",
      latitude: 18.5673,
      longitude: 73.9314,
      size: 200,
      school: "800m away",
      bus: "300m away",
      restaurant: "150m away",
      description: "Enjoy spacious living in this 3BHK apartment located in the desirable Kalyani Nagar area of Pune, close to essential amenities and green spaces.",
      ownerName: "Meera Deshmukh",
      ownerPhoto: "/o_6.jpg",
      renterResponsibility: "Renter responsible for utilities such as water and electricity.",
      petPolicy: "Small pets allowed with additional deposit.",
      propertyFees: "Must have income of at least three times the rent.",
    },
    {
      id: 7,
      title: "Chic Studio Apartment in Hyderabad",
      images: ["/s_7.jpg", "/s_7_1.jpg", "/s_7_2.jpg", "/s_7_3.jpg"],
      bedrooms: 1,
      bathrooms: 1,
      price: 5000000,
      address: "Banjara Hills, Hyderabad, Telangana",
      latitude: 17.4256,
      longitude: 78.4475,
      size: 60,
      school: "1km away",
      bus: "200m away",
      restaurant: "100m away",
      description: "This stylish studio apartment in Hyderabad’s upscale Banjara Hills offers a perfect blend of comfort and modern design for young professionals.",
      ownerName: "Arun Rao",
      ownerPhoto: "/o_7.jpg",
      renterResponsibility: "Tenant must cover utility expenses, including internet and utilities.",
      petPolicy: "Pets allowed with additional conditions.",
      propertyFees: "Three times the rent in monthly income required.",
    },
    {
      id: 8,
      title: "Luxury Penthouse in Mumbai",
      images: ["/s_8.jpg", "/s_8_1.jpg", "/s_8_2.jpg", "/s_8_3.jpg"],
      bedrooms: 5,
      bathrooms: 4,
      price: 75000000,
      address: "Bandra, Mumbai, Maharashtra",
      latitude: 19.0604,
      longitude: 72.8456,
      size: 500,
      school: "300m away",
      bus: "100m away",
      restaurant: "50m away",
      description: "Experience unparalleled luxury in this opulent penthouse located in Bandra, Mumbai. With breathtaking views and top-tier amenities, it is truly a premium residence.",
      ownerName: "Rajesh Menon",
      ownerPhoto: "/o_1.jpg",
      renterResponsibility: "Occupant is responsible for all utilities, including maintenance.",
      petPolicy: "Pets allowed with a deposit and specific restrictions.",
      propertyFees: "Must have total household income of three times the rent.",
    },{
    id: 9,
    title: "Affordable Housing in Ahmedabad",
    images: ["/s_9.jpg", "/s_9_1.jpg", "/s_9_2.jpg", "/s_9_3.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    price: 3500000,
    address: "Gota, Ahmedabad, Gujarat",
    size: 90,
    school: "500m away",
    bus: "300m away",
    restaurant: "200m away",
    description: "This budget-friendly 2BHK apartment in Ahmedabad offers practicality and comfort, situated in the well-connected Gota area with easy access to local amenities.",
    ownerName: "Snehal Patel",
    ownerPhoto: "/o_1.jpg",
    renterResponsibility: "Tenant is responsible for paying utilities like electricity and water.",
    petPolicy: "Pets are allowed with a nominal pet fee.",
    propertyFees: "Proof of income must be at least three times the rent amount.",
  },
  {
    id: 10,
    title: "Contemporary Home with Garden",
    images: ["/s_10.jpg", "/s_10_1.jpg", "/s_10_2.jpg", "/s_10_3.jpg"],
    bedrooms: 4,
    bathrooms: 3,
    price: 18000000,
    address: "Chennai, Tamil Nadu",
    size: 250,
    school: "1km away",
    bus: "400m away",
    restaurant: "300m away",
    description: "This contemporary home features a beautiful garden and modern design, offering a serene environment in the bustling city of Chennai.",
    ownerName: "Sita Rao",
    ownerPhoto: "/o_2.jpg",
    renterResponsibility: "Renter handles utility payments, including internet and maintenance.",
    petPolicy: "Pets allowed with a pet deposit and approval.",
    propertyFees: "Must provide evidence of income three times the rent.",
  },
  {
    id: 11,
    title: "Elegant Apartment in Kolkata",
    images: ["/s_11.jpg", "/s_11_1.jpg", "/s_11_2.jpg", "/s_11_3.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    price: 12000000,
    address: "Salt Lake, Kolkata, West Bengal",
    size: 160,
    school: "1km away",
    bus: "250m away",
    restaurant: "150m away",
    description: "This elegant apartment in Kolkata's Salt Lake offers modern living spaces with a touch of sophistication and easy access to city amenities.",
    ownerName: "Anita Gupta",
    ownerPhoto: "/o_3.jpg",
    renterResponsibility: "Utilities such as water, electricity, and gas are the tenant’s responsibility.",
    petPolicy: "Pets allowed with a deposit and prior approval.",
    propertyFees: "Income requirement is three times the rent amount.",
  },
  {
    id: 12,
    title: "Beautiful Farmhouse with Views",
    images: ["/s_12.jpg", "/s_1_1.jpg", "/s_2_1.jpg", "/s_3_1.jpg"],
    bedrooms: 5,
    bathrooms: 4,
    price: 22000000,
    address: "Nashik, Maharashtra",
    size: 500,
    school: "Nearby",
    bus: "1km away",
    restaurant: "500m away",
    description: "This beautiful farmhouse in Nashik offers expansive views, large living areas, and a tranquil setting perfect for those seeking a rural retreat.",
    ownerName: "Ravi Deshmukh",
    ownerPhoto: "/o_4.jpg",
    renterResponsibility: "Tenant is responsible for all utility payments, including maintenance costs.",
    petPolicy: "Pets are allowed with additional fees and conditions.",
    propertyFees: "Total household income must be three times the rent.",
  },
  {
    id: 13,
    title: "Sunny 2BHK in Noida",
    images: ["/s_13.jpg", "/s_1_2.jpg", "/s_2_2.jpg", "/s_3_2.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    price: 7000000,
    address: "Sector 18, Noida, Uttar Pradesh",
    size: 110,
    school: "500m away",
    bus: "200m away",
    restaurant: "100m away",
    description: "This sunny 2BHK apartment in Noida offers a bright and welcoming living space with easy access to local amenities and transport links.",
    ownerName: "Pooja Sharma",
    ownerPhoto: "/o_5.jpg",
    renterResponsibility: "Renter must handle utility expenses and maintenance fees.",
    petPolicy: "Pets allowed with a pet deposit and agreement.",
    propertyFees: "Proof of income required to be three times the rent.",
  },
  {
    id: 14,
    title: "Traditional Home in Jaipur",
    images: ["/s_14.jpg", "/s_1_3.jpg", "/s_2_3.jpg", "/s_3_3.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    price: 8000000,
    address: "C-Scheme, Jaipur, Rajasthan",
    size: 180,
    school: "1km away",
    bus: "300m away",
    restaurant: "200m away",
    description: "This traditional home in Jaipur blends classic design with modern amenities, providing a unique living experience in the historic city.",
    ownerName: "Deepak Mehta",
    ownerPhoto: "/o_6.jpg",
    renterResponsibility: "Tenant responsible for all utilities and related expenses.",
    petPolicy: "Pets are allowed with prior approval and a pet fee.",
    propertyFees: "Must have an income of three times the rent.",
  },
  {
    id: 15,
    title: "Modern Studio in Chandigarh",
    images: ["/s_15.jpg", "/s_1_1.jpg", "/s_2_1.jpg", "/s_3_1.jpg"],
    bedrooms: 1,
    bathrooms: 1,
    price: 6000000,
    address: "Sector 17, Chandigarh",
    size: 70,
    school: "Nearby",
    bus: "150m away",
    restaurant: "100m away",
    description: "This sleek and modern studio apartment in Chandigarh’s Sector 17 offers a stylish living space with convenient access to shopping and dining.",
    ownerName: "Karan Singh",
    ownerPhoto: "/o_7.jpg",
    renterResponsibility: "Renter handles utility costs including power and water.",
    petPolicy: "Pets allowed with a deposit and additional terms.",
    propertyFees: "Income requirement is three times the rent amount.",
  },
  {
    id: 16,
    title: "Luxurious 4BHK in Gurgaon",
    images: ["/s_16.jpg", "/s_1_2.jpg", "/s_2_2.jpg", "/s_3_2.jpg"],
    bedrooms: 4,
    bathrooms: 3,
    price: 30000000,
    address: "DLF Phase 5, Gurgaon, Haryana",
    size: 350,
    school: "1km away",
    bus: "200m away",
    restaurant: "150m away",
    description: "This opulent 4BHK home in Gurgaon’s DLF Phase 5 offers luxurious amenities and expansive living areas, perfect for a sophisticated lifestyle.",
    ownerName: "Sandeep Arora",
    ownerPhoto: "/o_1.jpg",
    renterResponsibility: "Tenant is responsible for all utilities and service charges.",
    petPolicy: "Pets are welcome with an additional deposit and pet agreement.",
    propertyFees: "Must prove household income is at least three times the rent.",
  },
  {
    id: 17,
    title: "Compact 1BHK in Faridabad",
    images: ["/s_17.jpg", "/s_1_3.jpg", "/s_2_3.jpg", "/s_3_3.jpg"],
    bedrooms: 1,
    bathrooms: 1,
    price: 4000000,
    address: "Sector 15, Faridabad, Haryana",
    size: 50,
    school: "500m away",
    bus: "300m away",
    restaurant: "200m away",
    description: "This compact yet comfortable 1BHK apartment in Faridabad offers practical living space with easy access to local amenities and transport.",
    ownerName: "Aarti Singh",
    ownerPhoto: "/o_2.jpg",
    renterResponsibility: "Renter responsible for all utility costs.",
    petPolicy: "Pets allowed with specific conditions and fees.",
    propertyFees: "Income must be three times the rent to qualify.",
  },
  {
    id: 18,
    title: "Stylish Loft in Bengaluru",
    images: ["/s_18.jpg", "/s_1_1.jpg", "/s_2_1.jpg", "/s_3_1.jpg"],
    bedrooms: 2,
    bathrooms: 1,
    price: 9000000,
    address: "Indiranagar, Bengaluru, Karnataka",
    size: 130,
    school: "1km away",
    bus: "200m away",
    restaurant: "100m away",
    description: "This chic loft in Bengaluru's vibrant Indiranagar area combines modern design with functionality, ideal for young professionals and small families.",
    ownerName: "Ravi Kumar",
    ownerPhoto: "/o_3.jpg",
    renterResponsibility: "Utilities such as water, electricity, and internet are the renter's responsibility.",
    petPolicy: "Pets allowed with a pet fee and specific conditions.",
    propertyFees: "Tenant must demonstrate a household income at least three times the rent amount.",
  },
  {
    id: 19,
    title: "Scenic Retreat in Coorg",
    images: ["/s_19.jpg", "/s_1_2.jpg", "/s_2_2.jpg", "/s_3_2.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    price: 13000000,
    address: "Coorg, Karnataka",
    size: 200,
    school: "1.5km away",
    bus: "500m away",
    restaurant: "300m away",
    description: "This serene retreat in Coorg offers a peaceful escape with scenic views, ideal for those seeking tranquility and a connection with nature.",
    ownerName: "Anand Rao",
    ownerPhoto: "/o_4.jpg",
    renterResponsibility: "Tenant must cover all utility costs including water, electricity, and garbage collection.",
    petPolicy: "Pets are allowed with a deposit and approval from the owner.",
    propertyFees: "Income must be at least three times the rent to qualify for this property.",
  },
  {
    id: 20,
    title: "Urban Apartment in Mumbai",
    images: ["/s_20.jpg", "/s_1_3.jpg", "/s_2_3.jpg", "/s_3_3.jpg"],
    bedrooms: 2,
    bathrooms: 2,
    price: 16000000,
    address: "Powai, Mumbai, Maharashtra",
    size: 140,
    school: "500m away",
    bus: "200m away",
    restaurant: "100m away",
    description: "This modern urban apartment in Powai combines convenience with luxury, offering a prime location and high-end features for a sophisticated lifestyle.",
    ownerName: "Ayesha Khan",
    ownerPhoto: "/o_5.jpg",
    renterResponsibility: "Renter is responsible for utility payments including gas, electricity, and water.",
    petPolicy: "Pets are allowed with prior approval and additional deposit.",
    propertyFees: "Proof of income must be three times the rent to qualify.",
  },

    {
      id: 21,
      type: 'rent',
      title: "Cozy Studio",
      images: ["/r_1.jpg", "/s_2_1.jpg", "/s_2_2.jpg", "/s_2_3.jpg"],
      bedrooms: 1,
      bathrooms: 1,
      price: 30000,
      address: "Downtown, Mumbai",
      latitude: 19.076,
      longitude: 72.8777,
      size: 50,
      school: "150m away",
      bus: "80m away",
      restaurant: "100m away",
      description: "A comfortable studio in the heart of Mumbai with all essential amenities.",
      ownerName: "Amit Sharma",
      ownerPhoto: "/o_1.jpg",
      renterResponsibility: "Utilities are the responsibility of the renter, including water, gas, and electricity.",
      petPolicy: "Pets are not allowed.",
      propertyFees: "Proof of household income that is at least twice the rent amount is required."
    },
    {
      id: 22,
      type: 'rent',
      title: "Modern 1BHK",
      images: ["/r_2.jpg", "/s_3_1.jpg", "/s_3_2.jpg", "/s_3_3.jpg"],
      bedrooms: 1,
      bathrooms: 1,
      price: 25000,
      address: "Suburbs, Bangalore",
      latitude: 12.9716,
      longitude: 77.5946,
      size: 75,
      school: "200m away",
      bus: "50m away",
      restaurant: "120m away",
      description: "A stylish and modern 1BHK apartment with easy access to public transport.",
      ownerName: "Karan Singh",
      ownerPhoto: "/o_2.jpg",
      renterResponsibility: "Renter is responsible for monthly maintenance fees.",
      petPolicy: "Pets allowed with prior approval and additional deposit.",
      propertyFees: "Income verification required, with proof of income at least twice the monthly rent."
    },
    {
      id: 23,
      type: 'rent',
      title: "Spacious 2BHK",
      images: ["/r_3.jpg", "/s_4_1.jpg", "/s_4_2.jpg", "/s_4_3.jpg"],
      bedrooms: 2,
      bathrooms: 1,
      price: 50000,
      address: "Near Park, Bangalore",
      latitude: 12.9352,
      longitude: 77.6245,
      size: 120,
      school: "300m away",
      bus: "60m away",
      restaurant: "200m away",
      description: "Spacious 2BHK apartment overlooking a lush green park.",
      ownerName: "Sonal Patel",
      ownerPhoto: "/o_3.jpg",
      renterResponsibility: "Water and electricity bills to be paid by the renter.",
      petPolicy: "Small pets allowed with additional deposit.",
      propertyFees: "Proof of household income that is at least three times the rent amount."
    },
    {
      id: 24,
      type: 'rent',
      title: "Comfortable 2BHK",
      images: ["/r_4.jpg", "/s_5_1.jpg", "/s_5_2.jpg", "/s_5_3.jpg"],
      bedrooms: 2,
      bathrooms: 2,
      price: 70000,
      address: "City Center, Mumbai",
      latitude: 19.0144,
      longitude: 72.8479,
      size: 140,
      school: "500m away",
      bus: "100m away",
      restaurant: "150m away",
      description: "A well-connected and comfortable 2BHK apartment in Mumbai's city center.",
      ownerName: "Vijay Desai",
      ownerPhoto: "/o_4.jpg",
      renterResponsibility: "Tenant must cover all utility costs and maintenance fees.",
      petPolicy: "No pets allowed.",
      propertyFees: "Must show proof of household income that is at least two times the rent amount."
    },
    {
      id: 25,
      type: 'rent',
      title: "Affordable 1BHK",
      images: ["/r_5.jpg", "/s_6_1.jpg", "/s_6_2.jpg", "/s_6_3.jpg"],
      bedrooms: 1,
      bathrooms: 1,
      price: 20000,
      address: "Quiet Area, Delhi",
      latitude: 28.7041,
      longitude: 77.1025,
      size: 65,
      school: "250m away",
      bus: "80m away",
      restaurant: "150m away",
      description: "An affordable 1BHK in a quiet and peaceful neighborhood in Delhi.",
      ownerName: "Rohit Kumar",
      ownerPhoto: "/o_5.jpg",
      renterResponsibility: "Water and electricity bills are tenant's responsibility.",
      petPolicy: "No pets allowed.",
      propertyFees: "Proof of income required to be at least twice the rent amount."
    },
    {
      id: 26,
      type: 'rent',
      title: "Elegant Studio",
      images: ["/r_6.jpg", "/s_7_1.jpg", "/s_7_2.jpg", "/s_7_3.jpg"],
      bedrooms: 1,
      bathrooms: 1,
      price: 35000,
      address: "Modern, Pune",
      latitude: 18.5204,
      longitude: 73.8567,
      size: 45,
      school: "400m away",
      bus: "70m away",
      restaurant: "120m away",
      description: "A stylish and elegant studio apartment in Pune's modern district.",
      ownerName: "Priya Jain",
      ownerPhoto: "/o_6.jpg",
      renterResponsibility: "Tenant responsible for all utilities.",
      petPolicy: "Small pets allowed with additional fee.",
      propertyFees: "Proof of income required to be at least three times the rent amount."
    },
    {
      id: 27,
      type: 'rent',
      title: "Bright 2BHK",
      images: ["/r_7.jpg", "/s_8_1.jpg", "/s_8_2.jpg", "/s_8_3.jpg"],
      bedrooms: 2,
      bathrooms: 1,
      price: 60000,
      address: "With Balcony, Hyderabad",
      latitude: 17.385,
      longitude: 78.4867,
      size: 115,
      school: "350m away",
      bus: "90m away",
      restaurant: "200m away",
      description: "A bright and airy 2BHK with a spacious balcony in Hyderabad.",
      ownerName: "Ankit Verma",
      ownerPhoto: "/o_7.jpg",
      renterResponsibility: "Utilities and maintenance fees are renter's responsibility.",
      petPolicy: "Pets allowed with prior approval.",
      propertyFees: "Household income must be at least twice the rent amount."
    },
    {
      id: 28,
      type: 'rent',
      title: "Stylish Studio",
      images: ["/r_8.jpg", "/s_9_1.jpg", "/s_9_2.jpg", "/s_9_3.jpg"],
      bedrooms: 1,
      bathrooms: 1,
      price: 40000,
      address: "High-Rise, Mumbai",
      latitude: 19.076,
      longitude: 72.8777,
      size: 55,
      school: "500m away",
      bus: "150m away",
      restaurant: "200m away",
      description: "A chic and stylish studio in a high-rise building in Mumbai.",
      ownerName: "Nisha Gupta",
      ownerPhoto: "/o_1.jpg",
      renterResponsibility: "Utilities to be paid by tenant.",
      petPolicy: "No pets allowed.",
      propertyFees: "Proof of income required, at least twice the rent amount."
    },
    {
      id: 29,
      type: 'rent',
      title: "Charming 2BHK",
      images: ["/r_9.jpg", "/s_10_1.jpg", "/s_10_2.jpg", "/s_10_3.jpg"],
      bedrooms: 2,
      bathrooms: 2,
      price: 75000,
      address: "Near Mall, Ahmedabad",
      latitude: 23.0225,
      longitude: 72.5714,
      size: 125,
      school: "300m away",
      bus: "100m away",
      restaurant: "150m away",
      description: "A charming 2BHK apartment located near a major shopping mall in Ahmedabad.",
      ownerName: "Meena Desai",
      ownerPhoto: "/o_2.jpg",
      renterResponsibility: "All utilities to be paid by tenant.",
      petPolicy: "Small pets allowed with prior approval.",
      propertyFees: "Must show proof of household income that is at least three times the rent amount."
    },
    {
      id: 30,
      type: 'rent',
      title: "Renovated 1BHK",
      images: ["/r_10.jpg", "/s_11_1.jpg", "/s_11_2.jpg", "/s_11_3.jpg"],
      bedrooms: 1,
      bathrooms: 1,
      price: 30000,
      address: "Historic, Chennai",
      latitude: 13.0827,
      longitude: 80.2707,
      size: 70,
      school: "400m away",
      bus: "100m away",
      restaurant: "200m away",
      description: "A beautifully renovated 1BHK apartment in a historic area of Chennai.",
      ownerName: "Anil Reddy",
      ownerPhoto: "/o_3.jpg",
      renterResponsibility: "Tenant responsible for all utilities and maintenance fees.",
      petPolicy: "Pets are not allowed.",
      propertyFees: "Proof of household income required to be at least twice the rent amount."
    },
    {
      id: 31,
      type: 'rent',
      title: "Comfy 2BHK",
      images: ["/r_11.jpg", "/s_12_1.jpg", "/s_12_2.jpg", "/s_12_3.jpg"],
      bedrooms: 2,
      bathrooms: 1,
      price: 55000,
      address: "Family Area, Kolkata",
      latitude: 22.5726,
      longitude: 88.3639,
      size: 110,
      school: "500m away",
      bus: "150m away",
      restaurant: "180m away",
      description: "A comfortable 2BHK apartment situated in a family-friendly area of Kolkata.",
      ownerName: "Suman Roy",
      ownerPhoto: "/o_4.jpg",
      renterResponsibility: "Utilities and maintenance fees are to be covered by the tenant.",
      petPolicy: "Small pets allowed with additional fee.",
      propertyFees: "Proof of income required to be at least twice the rent amount."
    }
  
    ]

export default Singlepagedata